package com.trainingportal.Transactions.valueObject;

// Generated Nov 25, 2014 11:19:12 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

import com.gargorg.Masters.valueObject.OrgUserMst;

/**
 * OrgAttendanceTxn generated by hbm2java
 */
public class OrgAttendanceTxn implements java.io.Serializable {

	private static final long serialVersionUID = 9056063870454321263L;
	private long attendanceTxnId;
	private OrgUserMst orgUserMstByCreatedUserId;
	private OrgUserMst orgUserMstByTraineeId;
	private OrgUserMst orgUserMstByUpdatedUserId;
	private long trainingCode;
	private Boolean attended;
	private boolean activateFlag;
	private Date createdDate;
	private Date updatedDate;

	public OrgAttendanceTxn() {
	}

	public OrgAttendanceTxn(long attendanceTxnId,
			OrgUserMst orgUserMstByCreatedUserId,
			OrgUserMst orgUserMstByTraineeId, long trainingCode,
			boolean activateFlag, Date createdDate) {
		this.attendanceTxnId = attendanceTxnId;
		this.orgUserMstByCreatedUserId = orgUserMstByCreatedUserId;
		this.orgUserMstByTraineeId = orgUserMstByTraineeId;
		this.trainingCode = trainingCode;
		this.activateFlag = activateFlag;
		this.createdDate = createdDate;
	}

	public OrgAttendanceTxn(long attendanceTxnId,
			OrgUserMst orgUserMstByCreatedUserId,
			OrgUserMst orgUserMstByTraineeId,
			OrgUserMst orgUserMstByUpdatedUserId, long trainingCode,
			Boolean attended, boolean activateFlag, Date createdDate,
			Date updatedDate) {
		this.attendanceTxnId = attendanceTxnId;
		this.orgUserMstByCreatedUserId = orgUserMstByCreatedUserId;
		this.orgUserMstByTraineeId = orgUserMstByTraineeId;
		this.orgUserMstByUpdatedUserId = orgUserMstByUpdatedUserId;
		this.trainingCode = trainingCode;
		this.attended = attended;
		this.activateFlag = activateFlag;
		this.createdDate = createdDate;
		this.updatedDate = updatedDate;
	}

	public long getAttendanceTxnId() {
		return this.attendanceTxnId;
	}

	public void setAttendanceTxnId(long attendanceTxnId) {
		this.attendanceTxnId = attendanceTxnId;
	}

	public OrgUserMst getOrgUserMstByCreatedUserId() {
		return this.orgUserMstByCreatedUserId;
	}

	public void setOrgUserMstByCreatedUserId(
			OrgUserMst orgUserMstByCreatedUserId) {
		this.orgUserMstByCreatedUserId = orgUserMstByCreatedUserId;
	}

	public OrgUserMst getOrgUserMstByTraineeId() {
		return this.orgUserMstByTraineeId;
	}

	public void setOrgUserMstByTraineeId(OrgUserMst orgUserMstByTraineeId) {
		this.orgUserMstByTraineeId = orgUserMstByTraineeId;
	}

	public OrgUserMst getOrgUserMstByUpdatedUserId() {
		return this.orgUserMstByUpdatedUserId;
	}

	public void setOrgUserMstByUpdatedUserId(
			OrgUserMst orgUserMstByUpdatedUserId) {
		this.orgUserMstByUpdatedUserId = orgUserMstByUpdatedUserId;
	}

	public long getTrainingCode() {
		return this.trainingCode;
	}

	public void setTrainingCode(long trainingCode) {
		this.trainingCode = trainingCode;
	}

	public Boolean getAttended() {
		return this.attended;
	}

	public void setAttended(Boolean attended) {
		this.attended = attended;
	}

	public boolean isActivateFlag() {
		return this.activateFlag;
	}

	public void setActivateFlag(boolean activateFlag) {
		this.activateFlag = activateFlag;
	}

	public Date getCreatedDate() {
		return this.createdDate;
	}

	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}

	public Date getUpdatedDate() {
		return this.updatedDate;
	}

	public void setUpdatedDate(Date updatedDate) {
		this.updatedDate = updatedDate;
	}

}
