package com.trainingportal.Transactions.valueObject;

// Generated Nov 25, 2014 11:19:12 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

import com.gargorg.Masters.valueObject.OrgUserMst;

/**
 * OrgTrainingTraineeMpg generated by hbm2java
 */
public class OrgTrainingTraineeMpg implements java.io.Serializable {

	private static final long serialVersionUID = 2714232417273889861L;
	
	private long trainingTraineeMpgId;
	private OrgUserMst orgUserMstByCreatedUserId;
	private OrgUserMst orgUserMstByTraineeId;
	private OrgUserMst orgUserMstByUpdatedUserId;
	private long trainingCode;
	private boolean activateFlag;
	private Date createdDate;
	private Date updatedDate;

	public OrgTrainingTraineeMpg() {
	}

	public OrgTrainingTraineeMpg(long trainingTraineeMpgId,
			OrgUserMst orgUserMstByCreatedUserId,
			OrgUserMst orgUserMstByTraineeId, long trainingCode,
			boolean activateFlag, Date createdDate) {
		this.trainingTraineeMpgId = trainingTraineeMpgId;
		this.orgUserMstByCreatedUserId = orgUserMstByCreatedUserId;
		this.orgUserMstByTraineeId = orgUserMstByTraineeId;
		this.trainingCode = trainingCode;
		this.activateFlag = activateFlag;
		this.createdDate = createdDate;
	}

	public OrgTrainingTraineeMpg(long trainingTraineeMpgId,
			OrgUserMst orgUserMstByCreatedUserId,
			OrgUserMst orgUserMstByTraineeId,
			OrgUserMst orgUserMstByUpdatedUserId, long trainingCode,
			boolean activateFlag, Date createdDate, Date updatedDate) {
		this.trainingTraineeMpgId = trainingTraineeMpgId;
		this.orgUserMstByCreatedUserId = orgUserMstByCreatedUserId;
		this.orgUserMstByTraineeId = orgUserMstByTraineeId;
		this.orgUserMstByUpdatedUserId = orgUserMstByUpdatedUserId;
		this.trainingCode = trainingCode;
		this.activateFlag = activateFlag;
		this.createdDate = createdDate;
		this.updatedDate = updatedDate;
	}

	public long getTrainingTraineeMpgId() {
		return this.trainingTraineeMpgId;
	}

	public void setTrainingTraineeMpgId(long trainingTraineeMpgId) {
		this.trainingTraineeMpgId = trainingTraineeMpgId;
	}

	public OrgUserMst getOrgUserMstByCreatedUserId() {
		return this.orgUserMstByCreatedUserId;
	}

	public void setOrgUserMstByCreatedUserId(
			OrgUserMst orgUserMstByCreatedUserId) {
		this.orgUserMstByCreatedUserId = orgUserMstByCreatedUserId;
	}

	public OrgUserMst getOrgUserMstByTraineeId() {
		return this.orgUserMstByTraineeId;
	}

	public void setOrgUserMstByTraineeId(OrgUserMst orgUserMstByTraineeId) {
		this.orgUserMstByTraineeId = orgUserMstByTraineeId;
	}

	public OrgUserMst getOrgUserMstByUpdatedUserId() {
		return this.orgUserMstByUpdatedUserId;
	}

	public void setOrgUserMstByUpdatedUserId(
			OrgUserMst orgUserMstByUpdatedUserId) {
		this.orgUserMstByUpdatedUserId = orgUserMstByUpdatedUserId;
	}

	public long getTrainingCode() {
		return this.trainingCode;
	}

	public void setTrainingCode(long trainingCode) {
		this.trainingCode = trainingCode;
	}

	public boolean isActivateFlag() {
		return this.activateFlag;
	}

	public void setActivateFlag(boolean activateFlag) {
		this.activateFlag = activateFlag;
	}

	public Date getCreatedDate() {
		return this.createdDate;
	}

	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}

	public Date getUpdatedDate() {
		return this.updatedDate;
	}

	public void setUpdatedDate(Date updatedDate) {
		this.updatedDate = updatedDate;
	}

}
