package com.gargorg.Masters.valueObject;
// Generated May 9, 2014 11:23:19 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * CmnLookupMst generated by hbm2java
 */
public class CmnLookupMst implements java.io.Serializable {

	private static final long serialVersionUID = 8972777501493744627L;
	private long lookupId;
	private OrgUserMst orgUserMstByCreatedUserId;
	private OrgUserMst orgUserMstByUpdatedUserId;
	private long lookupCode;
	private long parentLookupCode;
	private String lookupName;
	private boolean activateFlag;
	private Date createdDate;
	private Date updatedDate;

	public CmnLookupMst() {
	}

	public CmnLookupMst(long lookupId, OrgUserMst orgUserMstByCreatedUserId,
			long lookupCode, long parentLookupCode, String lookupName,
			boolean activateFlag, Date createdDate) {
		this.lookupId = lookupId;
		this.orgUserMstByCreatedUserId = orgUserMstByCreatedUserId;
		this.lookupCode = lookupCode;
		this.parentLookupCode = parentLookupCode;
		this.lookupName = lookupName;
		this.activateFlag = activateFlag;
		this.createdDate = createdDate;
	}

	public CmnLookupMst(long lookupId, OrgUserMst orgUserMstByCreatedUserId,
			OrgUserMst orgUserMstByUpdatedUserId, long lookupCode,
			long parentLookupCode, String lookupName, boolean activateFlag,
			Date createdDate, Date updatedDate) {
		this.lookupId = lookupId;
		this.orgUserMstByCreatedUserId = orgUserMstByCreatedUserId;
		this.orgUserMstByUpdatedUserId = orgUserMstByUpdatedUserId;
		this.lookupCode = lookupCode;
		this.parentLookupCode = parentLookupCode;
		this.lookupName = lookupName;
		this.activateFlag = activateFlag;
		this.createdDate = createdDate;
		this.updatedDate = updatedDate;
	}

	public long getLookupId() {
		return this.lookupId;
	}

	public void setLookupId(long lookupId) {
		this.lookupId = lookupId;
	}

	public OrgUserMst getOrgUserMstByCreatedUserId() {
		return this.orgUserMstByCreatedUserId;
	}

	public void setOrgUserMstByCreatedUserId(
			OrgUserMst orgUserMstByCreatedUserId) {
		this.orgUserMstByCreatedUserId = orgUserMstByCreatedUserId;
	}

	public OrgUserMst getOrgUserMstByUpdatedUserId() {
		return this.orgUserMstByUpdatedUserId;
	}

	public void setOrgUserMstByUpdatedUserId(
			OrgUserMst orgUserMstByUpdatedUserId) {
		this.orgUserMstByUpdatedUserId = orgUserMstByUpdatedUserId;
	}

	public long getLookupCode() {
		return this.lookupCode;
	}

	public void setLookupCode(long lookupCode) {
		this.lookupCode = lookupCode;
	}

	public long getParentLookupCode() {
		return this.parentLookupCode;
	}

	public void setParentLookupCode(long parentLookupCode) {
		this.parentLookupCode = parentLookupCode;
	}

	public String getLookupName() {
		return this.lookupName;
	}

	public void setLookupName(String lookupName) {
		this.lookupName = lookupName;
	}

	public boolean isActivateFlag() {
		return this.activateFlag;
	}

	public void setActivateFlag(boolean activateFlag) {
		this.activateFlag = activateFlag;
	}

	public Date getCreatedDate() {
		return this.createdDate;
	}

	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}

	public Date getUpdatedDate() {
		return this.updatedDate;
	}

	public void setUpdatedDate(Date updatedDate) {
		this.updatedDate = updatedDate;
	}

}
