package com.gargorg.Masters.valueObject;
// Generated May 9, 2014 11:23:19 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * CmnLookupDetailsRlt generated by hbm2java
 */
public class CmnLookupDetailsRlt implements java.io.Serializable {

	private static final long serialVersionUID = 2766598010600671404L;
	private long lookupDetailId;
	private CmnLanguageMst cmnLanguageMst;
	private OrgUserMst orgUserMstByCreatedUserId;
	private OrgUserMst orgUserMstByUpdatedUserId;
	private long lookupCode;
	private String lookupShortName;
	private String lookupDesc;
	private boolean activateFlag;
	private Date createdDate;
	private Date updatedDate;

	public CmnLookupDetailsRlt() {
	}

	public CmnLookupDetailsRlt(long lookupDetailId,
			CmnLanguageMst cmnLanguageMst,
			OrgUserMst orgUserMstByCreatedUserId, long lookupCode,
			String lookupShortName, String lookupDesc, boolean activateFlag,
			Date createdDate) {
		this.lookupDetailId = lookupDetailId;
		this.cmnLanguageMst = cmnLanguageMst;
		this.orgUserMstByCreatedUserId = orgUserMstByCreatedUserId;
		this.lookupCode = lookupCode;
		this.lookupShortName = lookupShortName;
		this.lookupDesc = lookupDesc;
		this.activateFlag = activateFlag;
		this.createdDate = createdDate;
	}

	public CmnLookupDetailsRlt(long lookupDetailId,
			CmnLanguageMst cmnLanguageMst,
			OrgUserMst orgUserMstByCreatedUserId,
			OrgUserMst orgUserMstByUpdatedUserId, long lookupCode,
			String lookupShortName, String lookupDesc, boolean activateFlag,
			Date createdDate, Date updatedDate) {
		this.lookupDetailId = lookupDetailId;
		this.cmnLanguageMst = cmnLanguageMst;
		this.orgUserMstByCreatedUserId = orgUserMstByCreatedUserId;
		this.orgUserMstByUpdatedUserId = orgUserMstByUpdatedUserId;
		this.lookupCode = lookupCode;
		this.lookupShortName = lookupShortName;
		this.lookupDesc = lookupDesc;
		this.activateFlag = activateFlag;
		this.createdDate = createdDate;
		this.updatedDate = updatedDate;
	}

	public long getLookupDetailId() {
		return this.lookupDetailId;
	}

	public void setLookupDetailId(long lookupDetailId) {
		this.lookupDetailId = lookupDetailId;
	}

	public CmnLanguageMst getCmnLanguageMst() {
		return this.cmnLanguageMst;
	}

	public void setCmnLanguageMst(CmnLanguageMst cmnLanguageMst) {
		this.cmnLanguageMst = cmnLanguageMst;
	}

	public OrgUserMst getOrgUserMstByCreatedUserId() {
		return this.orgUserMstByCreatedUserId;
	}

	public void setOrgUserMstByCreatedUserId(
			OrgUserMst orgUserMstByCreatedUserId) {
		this.orgUserMstByCreatedUserId = orgUserMstByCreatedUserId;
	}

	public OrgUserMst getOrgUserMstByUpdatedUserId() {
		return this.orgUserMstByUpdatedUserId;
	}

	public void setOrgUserMstByUpdatedUserId(
			OrgUserMst orgUserMstByUpdatedUserId) {
		this.orgUserMstByUpdatedUserId = orgUserMstByUpdatedUserId;
	}

	public long getLookupCode() {
		return this.lookupCode;
	}

	public void setLookupCode(long lookupCode) {
		this.lookupCode = lookupCode;
	}

	public String getLookupShortName() {
		return this.lookupShortName;
	}

	public void setLookupShortName(String lookupShortName) {
		this.lookupShortName = lookupShortName;
	}

	public String getLookupDesc() {
		return this.lookupDesc;
	}

	public void setLookupDesc(String lookupDesc) {
		this.lookupDesc = lookupDesc;
	}

	public boolean isActivateFlag() {
		return this.activateFlag;
	}

	public void setActivateFlag(boolean activateFlag) {
		this.activateFlag = activateFlag;
	}

	public Date getCreatedDate() {
		return this.createdDate;
	}

	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}

	public Date getUpdatedDate() {
		return this.updatedDate;
	}

	public void setUpdatedDate(Date updatedDate) {
		this.updatedDate = updatedDate;
	}

}
