package com.gargorg.Masters.valueObject;
// Generated May 9, 2014 11:23:19 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * OrgElementMst generated by hbm2java
 */
public class OrgElementMst implements java.io.Serializable {

	private static final long serialVersionUID = -1262719986294228830L;
	private long elementId;
	private OrgUserMst orgUserMstByCreatedUserId;
	private OrgUserMst orgUserMstByUpdatedUserId;
	private long elementCode;
	private long elementParentCode;
	private long elementType;
	private String elementUrl;
	private long elementOrder;
	private boolean activateFlag;
	private Date createdDate;
	private Date updatedDate;
	private boolean editable;

	public OrgElementMst() {
	}

	public OrgElementMst(long elementId, OrgUserMst orgUserMstByCreatedUserId,
			long elementCode, long elementParentCode, long elementType,
			long elementOrder, boolean activateFlag, Date createdDate,
			boolean editable) {
		this.elementId = elementId;
		this.orgUserMstByCreatedUserId = orgUserMstByCreatedUserId;
		this.elementCode = elementCode;
		this.elementParentCode = elementParentCode;
		this.elementType = elementType;
		this.elementOrder = elementOrder;
		this.activateFlag = activateFlag;
		this.createdDate = createdDate;
		this.editable = editable;
	}

	public OrgElementMst(long elementId, OrgUserMst orgUserMstByCreatedUserId,
			OrgUserMst orgUserMstByUpdatedUserId, long elementCode,
			long elementParentCode, long elementType, String elementUrl,
			long elementOrder, boolean activateFlag, Date createdDate,
			Date updatedDate, boolean editable) {
		this.elementId = elementId;
		this.orgUserMstByCreatedUserId = orgUserMstByCreatedUserId;
		this.orgUserMstByUpdatedUserId = orgUserMstByUpdatedUserId;
		this.elementCode = elementCode;
		this.elementParentCode = elementParentCode;
		this.elementType = elementType;
		this.elementUrl = elementUrl;
		this.elementOrder = elementOrder;
		this.activateFlag = activateFlag;
		this.createdDate = createdDate;
		this.updatedDate = updatedDate;
		this.editable = editable;
	}

	public long getElementId() {
		return this.elementId;
	}

	public void setElementId(long elementId) {
		this.elementId = elementId;
	}

	public OrgUserMst getOrgUserMstByCreatedUserId() {
		return this.orgUserMstByCreatedUserId;
	}

	public void setOrgUserMstByCreatedUserId(
			OrgUserMst orgUserMstByCreatedUserId) {
		this.orgUserMstByCreatedUserId = orgUserMstByCreatedUserId;
	}

	public OrgUserMst getOrgUserMstByUpdatedUserId() {
		return this.orgUserMstByUpdatedUserId;
	}

	public void setOrgUserMstByUpdatedUserId(
			OrgUserMst orgUserMstByUpdatedUserId) {
		this.orgUserMstByUpdatedUserId = orgUserMstByUpdatedUserId;
	}

	public long getElementCode() {
		return this.elementCode;
	}

	public void setElementCode(long elementCode) {
		this.elementCode = elementCode;
	}

	public long getElementParentCode() {
		return this.elementParentCode;
	}

	public void setElementParentCode(long elementParentCode) {
		this.elementParentCode = elementParentCode;
	}

	public long getElementType() {
		return this.elementType;
	}

	public void setElementType(long elementType) {
		this.elementType = elementType;
	}

	public String getElementUrl() {
		return this.elementUrl;
	}

	public void setElementUrl(String elementUrl) {
		this.elementUrl = elementUrl;
	}

	public long getElementOrder() {
		return this.elementOrder;
	}

	public void setElementOrder(long elementOrder) {
		this.elementOrder = elementOrder;
	}

	public boolean isActivateFlag() {
		return this.activateFlag;
	}

	public void setActivateFlag(boolean activateFlag) {
		this.activateFlag = activateFlag;
	}

	public Date getCreatedDate() {
		return this.createdDate;
	}

	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}

	public Date getUpdatedDate() {
		return this.updatedDate;
	}

	public void setUpdatedDate(Date updatedDate) {
		this.updatedDate = updatedDate;
	}

	public boolean isEditable() {
		return this.editable;
	}

	public void setEditable(boolean editable) {
		this.editable = editable;
	}
}
