package com.gargorg.Masters.valueObject;
// Generated May 9, 2014 11:23:19 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * OrgEmpMst generated by hbm2java
 */
public class OrgEmpMst implements java.io.Serializable {

	private static final long serialVersionUID = -1397291625594726679L;
	private long empId;
	private CmnLanguageMst cmnLanguageMst;
	private OrgUserMst orgUserMstByUserId;
	private OrgUserMst orgUserMstByCreatedUserId;
	private OrgUserMst orgUserMstByUpdatedUserId;
	private String empGender;
	private String empFname;
	private String empMname;
	private String empLname;
	private Date empDob;
	private Date empDoj;
	private boolean activateFlag;
	private String email;
	private Date createdDate;
	private Date updatedDate;

	public OrgEmpMst() {
	}

	public OrgEmpMst(long empId, CmnLanguageMst cmnLanguageMst,
			OrgUserMst orgUserMstByUserId,
			OrgUserMst orgUserMstByCreatedUserId, String empGender,
			String empFname, String empLname, Date empDob, Date empDoj,
			boolean activateFlag, String email, Date createdDate) {
		this.empId = empId;
		this.cmnLanguageMst = cmnLanguageMst;
		this.orgUserMstByUserId = orgUserMstByUserId;
		this.orgUserMstByCreatedUserId = orgUserMstByCreatedUserId;
		this.empGender = empGender;
		this.empFname = empFname;
		this.empLname = empLname;
		this.empDob = empDob;
		this.empDoj = empDoj;
		this.activateFlag = activateFlag;
		this.email = email;
		this.createdDate = createdDate;
	}

	public OrgEmpMst(long empId, CmnLanguageMst cmnLanguageMst,
			OrgUserMst orgUserMstByUserId,
			OrgUserMst orgUserMstByCreatedUserId,
			OrgUserMst orgUserMstByUpdatedUserId, String empGender,
			String empFname, String empMname, String empLname, Date empDob,
			Date empDoj, boolean activateFlag, String email, Date createdDate,
			Date updatedDate) {
		this.empId = empId;
		this.cmnLanguageMst = cmnLanguageMst;
		this.orgUserMstByUserId = orgUserMstByUserId;
		this.orgUserMstByCreatedUserId = orgUserMstByCreatedUserId;
		this.orgUserMstByUpdatedUserId = orgUserMstByUpdatedUserId;
		this.empGender = empGender;
		this.empFname = empFname;
		this.empMname = empMname;
		this.empLname = empLname;
		this.empDob = empDob;
		this.empDoj = empDoj;
		this.activateFlag = activateFlag;
		this.email = email;
		this.createdDate = createdDate;
		this.updatedDate = updatedDate;
	}

	public long getEmpId() {
		return this.empId;
	}

	public void setEmpId(long empId) {
		this.empId = empId;
	}

	public CmnLanguageMst getCmnLanguageMst() {
		return this.cmnLanguageMst;
	}

	public void setCmnLanguageMst(CmnLanguageMst cmnLanguageMst) {
		this.cmnLanguageMst = cmnLanguageMst;
	}

	public OrgUserMst getOrgUserMstByUserId() {
		return this.orgUserMstByUserId;
	}

	public void setOrgUserMstByUserId(OrgUserMst orgUserMstByUserId) {
		this.orgUserMstByUserId = orgUserMstByUserId;
	}

	public OrgUserMst getOrgUserMstByCreatedUserId() {
		return this.orgUserMstByCreatedUserId;
	}

	public void setOrgUserMstByCreatedUserId(
			OrgUserMst orgUserMstByCreatedUserId) {
		this.orgUserMstByCreatedUserId = orgUserMstByCreatedUserId;
	}

	public OrgUserMst getOrgUserMstByUpdatedUserId() {
		return this.orgUserMstByUpdatedUserId;
	}

	public void setOrgUserMstByUpdatedUserId(
			OrgUserMst orgUserMstByUpdatedUserId) {
		this.orgUserMstByUpdatedUserId = orgUserMstByUpdatedUserId;
	}

	public String getEmpGender() {
		return this.empGender;
	}

	public void setEmpGender(String empGender) {
		this.empGender = empGender;
	}

	public String getEmpFname() {
		return this.empFname;
	}

	public void setEmpFname(String empFname) {
		this.empFname = empFname;
	}

	public String getEmpMname() {
		return this.empMname;
	}

	public void setEmpMname(String empMname) {
		this.empMname = empMname;
	}

	public String getEmpLname() {
		return this.empLname;
	}

	public void setEmpLname(String empLname) {
		this.empLname = empLname;
	}

	public Date getEmpDob() {
		return this.empDob;
	}

	public void setEmpDob(Date empDob) {
		this.empDob = empDob;
	}

	public Date getEmpDoj() {
		return this.empDoj;
	}

	public void setEmpDoj(Date empDoj) {
		this.empDoj = empDoj;
	}

	public boolean isActivateFlag() {
		return this.activateFlag;
	}

	public void setActivateFlag(boolean activateFlag) {
		this.activateFlag = activateFlag;
	}

	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public Date getCreatedDate() {
		return this.createdDate;
	}

	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}

	public Date getUpdatedDate() {
		return this.updatedDate;
	}

	public void setUpdatedDate(Date updatedDate) {
		this.updatedDate = updatedDate;
	}

}
