package com.gargorg.Masters.valueObject;
// Generated May 9, 2014 11:23:19 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * OrgRoleDetailsRlt generated by hbm2java
 */
public class OrgRoleDetailsRlt implements java.io.Serializable {

	private static final long serialVersionUID = -5845689065610640600L;
	private long roleDetailId;
	private CmnLanguageMst cmnLanguageMst;
	private OrgUserMst orgUserMstByCreatedUserId;
	private OrgUserMst orgUserMstByUpdatedUserId;
	private long roleCode;
	private String roleName;
	private String roleShortName;
	private String roleDesc;
	private boolean activateFlag;
	private Date createdDate;
	private Date updatedDate;

	public OrgRoleDetailsRlt() {
	}

	public OrgRoleDetailsRlt(long roleDetailId, CmnLanguageMst cmnLanguageMst,
			OrgUserMst orgUserMstByCreatedUserId, long roleCode,
			String roleName, String roleShortName, String roleDesc,
			boolean activateFlag, Date createdDate) {
		this.roleDetailId = roleDetailId;
		this.cmnLanguageMst = cmnLanguageMst;
		this.orgUserMstByCreatedUserId = orgUserMstByCreatedUserId;
		this.roleCode = roleCode;
		this.roleName = roleName;
		this.roleShortName = roleShortName;
		this.roleDesc = roleDesc;
		this.activateFlag = activateFlag;
		this.createdDate = createdDate;
	}

	public OrgRoleDetailsRlt(long roleDetailId, CmnLanguageMst cmnLanguageMst,
			OrgUserMst orgUserMstByCreatedUserId,
			OrgUserMst orgUserMstByUpdatedUserId, long roleCode,
			String roleName, String roleShortName, String roleDesc,
			boolean activateFlag, Date createdDate, Date updatedDate) {
		this.roleDetailId = roleDetailId;
		this.cmnLanguageMst = cmnLanguageMst;
		this.orgUserMstByCreatedUserId = orgUserMstByCreatedUserId;
		this.orgUserMstByUpdatedUserId = orgUserMstByUpdatedUserId;
		this.roleCode = roleCode;
		this.roleName = roleName;
		this.roleShortName = roleShortName;
		this.roleDesc = roleDesc;
		this.activateFlag = activateFlag;
		this.createdDate = createdDate;
		this.updatedDate = updatedDate;
	}

	public long getRoleDetailId() {
		return this.roleDetailId;
	}

	public void setRoleDetailId(long roleDetailId) {
		this.roleDetailId = roleDetailId;
	}

	public CmnLanguageMst getCmnLanguageMst() {
		return this.cmnLanguageMst;
	}

	public void setCmnLanguageMst(CmnLanguageMst cmnLanguageMst) {
		this.cmnLanguageMst = cmnLanguageMst;
	}

	public OrgUserMst getOrgUserMstByCreatedUserId() {
		return this.orgUserMstByCreatedUserId;
	}

	public void setOrgUserMstByCreatedUserId(
			OrgUserMst orgUserMstByCreatedUserId) {
		this.orgUserMstByCreatedUserId = orgUserMstByCreatedUserId;
	}

	public OrgUserMst getOrgUserMstByUpdatedUserId() {
		return this.orgUserMstByUpdatedUserId;
	}

	public void setOrgUserMstByUpdatedUserId(
			OrgUserMst orgUserMstByUpdatedUserId) {
		this.orgUserMstByUpdatedUserId = orgUserMstByUpdatedUserId;
	}

	public long getRoleCode() {
		return this.roleCode;
	}

	public void setRoleCode(long roleCode) {
		this.roleCode = roleCode;
	}

	public String getRoleName() {
		return this.roleName;
	}

	public void setRoleName(String roleName) {
		this.roleName = roleName;
	}

	public String getRoleShortName() {
		return this.roleShortName;
	}

	public void setRoleShortName(String roleShortName) {
		this.roleShortName = roleShortName;
	}

	public String getRoleDesc() {
		return this.roleDesc;
	}

	public void setRoleDesc(String roleDesc) {
		this.roleDesc = roleDesc;
	}

	public boolean isActivateFlag() {
		return this.activateFlag;
	}

	public void setActivateFlag(boolean activateFlag) {
		this.activateFlag = activateFlag;
	}

	public Date getCreatedDate() {
		return this.createdDate;
	}

	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}

	public Date getUpdatedDate() {
		return this.updatedDate;
	}

	public void setUpdatedDate(Date updatedDate) {
		this.updatedDate = updatedDate;
	}

}
