package com.gargorg.Masters.valueObject;
// Generated May 9, 2014 11:23:19 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * OrgRoleElementRlt generated by hbm2java
 */
public class OrgRoleElementRlt implements java.io.Serializable {

	private static final long serialVersionUID = -3050286874426578661L;
	private long roleElementId;
	private OrgUserMst orgUserMstByCreatedUserId;
	private OrgUserMst orgUserMstByUpdatedUserId;
	private long roleCode;
	private long elementCode;
	private Date createdDate;
	private Date updatedDate;
	private boolean activateFlag;

	public OrgRoleElementRlt() {
	}

	public OrgRoleElementRlt(long roleElementId,
			OrgUserMst orgUserMstByCreatedUserId, long roleCode,
			long elementCode, Date createdDate, boolean activateFlag) {
		this.roleElementId = roleElementId;
		this.orgUserMstByCreatedUserId = orgUserMstByCreatedUserId;
		this.roleCode = roleCode;
		this.elementCode = elementCode;
		this.createdDate = createdDate;
		this.activateFlag = activateFlag;
	}

	public OrgRoleElementRlt(long roleElementId,
			OrgUserMst orgUserMstByCreatedUserId,
			OrgUserMst orgUserMstByUpdatedUserId, long roleCode,
			long elementCode, Date createdDate, Date updatedDate,
			boolean activateFlag) {
		this.roleElementId = roleElementId;
		this.orgUserMstByCreatedUserId = orgUserMstByCreatedUserId;
		this.orgUserMstByUpdatedUserId = orgUserMstByUpdatedUserId;
		this.roleCode = roleCode;
		this.elementCode = elementCode;
		this.createdDate = createdDate;
		this.updatedDate = updatedDate;
		this.activateFlag = activateFlag;
	}

	public long getRoleElementId() {
		return this.roleElementId;
	}

	public void setRoleElementId(long roleElementId) {
		this.roleElementId = roleElementId;
	}

	public OrgUserMst getOrgUserMstByCreatedUserId() {
		return this.orgUserMstByCreatedUserId;
	}

	public void setOrgUserMstByCreatedUserId(
			OrgUserMst orgUserMstByCreatedUserId) {
		this.orgUserMstByCreatedUserId = orgUserMstByCreatedUserId;
	}

	public OrgUserMst getOrgUserMstByUpdatedUserId() {
		return this.orgUserMstByUpdatedUserId;
	}

	public void setOrgUserMstByUpdatedUserId(
			OrgUserMst orgUserMstByUpdatedUserId) {
		this.orgUserMstByUpdatedUserId = orgUserMstByUpdatedUserId;
	}

	public long getRoleCode() {
		return this.roleCode;
	}

	public void setRoleCode(long roleCode) {
		this.roleCode = roleCode;
	}

	public long getElementCode() {
		return this.elementCode;
	}

	public void setElementCode(long elementCode) {
		this.elementCode = elementCode;
	}

	public Date getCreatedDate() {
		return this.createdDate;
	}

	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}

	public Date getUpdatedDate() {
		return this.updatedDate;
	}

	public void setUpdatedDate(Date updatedDate) {
		this.updatedDate = updatedDate;
	}

	public boolean isActivateFlag() {
		return this.activateFlag;
	}

	public void setActivateFlag(boolean activateFlag) {
		this.activateFlag = activateFlag;
	}

}
