package com.gargorg.Masters.valueObject;
// Generated May 9, 2014 11:23:19 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * OrgUserRoleRlt generated by hbm2java
 */
public class OrgUserRoleRlt implements java.io.Serializable {

	private static final long serialVersionUID = -2903851863452531022L;
	private long userRoleId;
	private OrgUserMst orgUserMstByUserId;
	private OrgUserMst orgUserMstByCreatedUserId;
	private OrgUserMst orgUserMstByUpdatedUserId;
	private long roleCode;
	private boolean activateFlag;
	private Date createdDate;
	private Date updatedDate;

	public OrgUserRoleRlt() {
	}

	public OrgUserRoleRlt(long userRoleId, OrgUserMst orgUserMstByUserId,
			OrgUserMst orgUserMstByCreatedUserId, long roleCode,
			boolean activateFlag, Date createdDate) {
		this.userRoleId = userRoleId;
		this.orgUserMstByUserId = orgUserMstByUserId;
		this.orgUserMstByCreatedUserId = orgUserMstByCreatedUserId;
		this.roleCode = roleCode;
		this.activateFlag = activateFlag;
		this.createdDate = createdDate;
	}

	public OrgUserRoleRlt(long userRoleId, OrgUserMst orgUserMstByUserId,
			OrgUserMst orgUserMstByCreatedUserId,
			OrgUserMst orgUserMstByUpdatedUserId, long roleCode,
			boolean activateFlag, Date createdDate, Date updatedDate) {
		this.userRoleId = userRoleId;
		this.orgUserMstByUserId = orgUserMstByUserId;
		this.orgUserMstByCreatedUserId = orgUserMstByCreatedUserId;
		this.orgUserMstByUpdatedUserId = orgUserMstByUpdatedUserId;
		this.roleCode = roleCode;
		this.activateFlag = activateFlag;
		this.createdDate = createdDate;
		this.updatedDate = updatedDate;
	}

	public long getUserRoleId() {
		return this.userRoleId;
	}

	public void setUserRoleId(long userRoleId) {
		this.userRoleId = userRoleId;
	}

	public OrgUserMst getOrgUserMstByUserId() {
		return this.orgUserMstByUserId;
	}

	public void setOrgUserMstByUserId(OrgUserMst orgUserMstByUserId) {
		this.orgUserMstByUserId = orgUserMstByUserId;
	}

	public OrgUserMst getOrgUserMstByCreatedUserId() {
		return this.orgUserMstByCreatedUserId;
	}

	public void setOrgUserMstByCreatedUserId(
			OrgUserMst orgUserMstByCreatedUserId) {
		this.orgUserMstByCreatedUserId = orgUserMstByCreatedUserId;
	}

	public OrgUserMst getOrgUserMstByUpdatedUserId() {
		return this.orgUserMstByUpdatedUserId;
	}

	public void setOrgUserMstByUpdatedUserId(
			OrgUserMst orgUserMstByUpdatedUserId) {
		this.orgUserMstByUpdatedUserId = orgUserMstByUpdatedUserId;
	}

	public long getRoleCode() {
		return this.roleCode;
	}

	public void setRoleCode(long roleCode) {
		this.roleCode = roleCode;
	}

	public boolean isActivateFlag() {
		return this.activateFlag;
	}

	public void setActivateFlag(boolean activateFlag) {
		this.activateFlag = activateFlag;
	}

	public Date getCreatedDate() {
		return this.createdDate;
	}

	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}

	public Date getUpdatedDate() {
		return this.updatedDate;
	}

	public void setUpdatedDate(Date updatedDate) {
		this.updatedDate = updatedDate;
	}

}
