package com.gargorg.Masters.valueObject;

// Generated May 9, 2014 11:23:19 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * OrgUserMst generated by hbm2java
 */
public class OrgUserMst implements java.io.Serializable {

	private static final long serialVersionUID = -7626481497573763603L;
	private long userId;
	private OrgUserMst orgUserMstByCreatedUserId;
	private OrgUserMst orgUserMstByUpdatedUserId;
	private String userName;
	private String password;
	private boolean activateFlag;
	private Date createdDate;
	private Date updatedDate;
	private String firstlogin;
	private Date pwdchangedDate;
	private long secretQueCode;
	private String secretAnswer;
	private long invalidLoginCnt;
	private Date unlockTime;
	private boolean otpEnabled;
	private Long otp;
	private Date otpValidity;
	private long regMobileNo;
	private Set orgUserRoleRltsForUserId = new HashSet(0);
	private Set orgRoleMstsForCreatedUserId = new HashSet(0);
	private Set orgEmpMstsForCreatedUserId = new HashSet(0);
	private Set cmnLookupMstsForUpdatedUserId = new HashSet(0);
	private Set orgUserImageMstsForUpdatedUserId = new HashSet(0);
	private Set orgUserMstsForCreatedUserId = new HashSet(0);
	private Set cmnLanguageMstsForCreatedUserId = new HashSet(0);
	private Set orgUserImageMstsForCreatedUserId = new HashSet(0);
	private Set orgUserMstsForUpdatedUserId = new HashSet(0);
	private Set orgUserRoleRltsForUpdatedUserId = new HashSet(0);
	private Set orgRoleElementRltsForCreatedUserId = new HashSet(0);
	private Set orgUserRoleRltsForCreatedUserId = new HashSet(0);
	private Set orgEmpMstsForUpdatedUserId = new HashSet(0);
	private Set orgRoleElementRltsForUpdatedUserId = new HashSet(0);
	private Set orgElementDetailsRltsForUpdatedUserId = new HashSet(0);
	private Set orgElementDetailsRltsForCreatedUserId = new HashSet(0);
	private Set orgUserImageMstsForUserId = new HashSet(0);
	private Set orgElementMstsForCreatedUserId = new HashSet(0);
	private Set orgRoleMstsForUpdatedUserId = new HashSet(0);
	private Set cmnLookupMstsForCreatedUserId = new HashSet(0);
	private Set cmnLookupDetailsRltsForCreatedUserId = new HashSet(0);
	private Set orgElementMstsForUpdatedUserId = new HashSet(0);
	private Set cmnLookupDetailsRltsForUpdatedUserId = new HashSet(0);
	private Set orgRoleDetailsRltsForCreatedUserId = new HashSet(0);
	private Set orgRoleDetailsRltsForUpdatedUserId = new HashSet(0);
	private Set orgEmpMstsForUserId = new HashSet(0);
	private Set cmnLanguageMstsForUpdatedUserId = new HashSet(0);

	public OrgUserMst() {
	}

	public OrgUserMst(long userId, OrgUserMst orgUserMstByCreatedUserId,
			String userName, String password, boolean activateFlag,
			Date createdDate, long secretQueCode, String secretAnswer,
			long invalidLoginCnt, boolean otpEnabled, long regMobileNo) {
		this.userId = userId;
		this.orgUserMstByCreatedUserId = orgUserMstByCreatedUserId;
		this.userName = userName;
		this.password = password;
		this.activateFlag = activateFlag;
		this.createdDate = createdDate;
		this.secretQueCode = secretQueCode;
		this.secretAnswer = secretAnswer;
		this.invalidLoginCnt = invalidLoginCnt;
		this.otpEnabled = otpEnabled;
		this.regMobileNo = regMobileNo;
	}

	public OrgUserMst(long userId, OrgUserMst orgUserMstByCreatedUserId,
			OrgUserMst orgUserMstByUpdatedUserId, String userName,
			String password, boolean activateFlag, Date createdDate,
			Date updatedDate, String firstlogin, Date pwdchangedDate,
			long secretQueCode, String secretAnswer, long invalidLoginCnt,
			Date unlockTime, boolean otpEnabled, Long otp, Date otpValidity,
			long regMobileNo, Set orgUserRoleRltsForUserId,
			Set orgRoleMstsForCreatedUserId, Set orgEmpMstsForCreatedUserId,
			Set cmnLookupMstsForUpdatedUserId,
			Set orgUserImageMstsForUpdatedUserId,
			Set orgUserMstsForCreatedUserId,
			Set cmnLanguageMstsForCreatedUserId,
			Set orgUserImageMstsForCreatedUserId,
			Set orgUserMstsForUpdatedUserId,
			Set orgUserRoleRltsForUpdatedUserId,
			Set orgRoleElementRltsForCreatedUserId,
			Set orgUserRoleRltsForCreatedUserId,
			Set orgEmpMstsForUpdatedUserId,
			Set orgRoleElementRltsForUpdatedUserId,
			Set orgElementDetailsRltsForUpdatedUserId,
			Set orgElementDetailsRltsForCreatedUserId,
			Set orgUserImageMstsForUserId, Set orgElementMstsForCreatedUserId,
			Set orgRoleMstsForUpdatedUserId, Set cmnLookupMstsForCreatedUserId,
			Set cmnLookupDetailsRltsForCreatedUserId,
			Set orgElementMstsForUpdatedUserId,
			Set cmnLookupDetailsRltsForUpdatedUserId,
			Set orgRoleDetailsRltsForCreatedUserId,
			Set orgRoleDetailsRltsForUpdatedUserId, Set orgEmpMstsForUserId,
			Set cmnLanguageMstsForUpdatedUserId) {
		this.userId = userId;
		this.orgUserMstByCreatedUserId = orgUserMstByCreatedUserId;
		this.orgUserMstByUpdatedUserId = orgUserMstByUpdatedUserId;
		this.userName = userName;
		this.password = password;
		this.activateFlag = activateFlag;
		this.createdDate = createdDate;
		this.updatedDate = updatedDate;
		this.firstlogin = firstlogin;
		this.pwdchangedDate = pwdchangedDate;
		this.secretQueCode = secretQueCode;
		this.secretAnswer = secretAnswer;
		this.invalidLoginCnt = invalidLoginCnt;
		this.unlockTime = unlockTime;
		this.otpEnabled = otpEnabled;
		this.otp = otp;
		this.otpValidity = otpValidity;
		this.regMobileNo = regMobileNo;
		this.orgUserRoleRltsForUserId = orgUserRoleRltsForUserId;
		this.orgRoleMstsForCreatedUserId = orgRoleMstsForCreatedUserId;
		this.orgEmpMstsForCreatedUserId = orgEmpMstsForCreatedUserId;
		this.cmnLookupMstsForUpdatedUserId = cmnLookupMstsForUpdatedUserId;
		this.orgUserImageMstsForUpdatedUserId = orgUserImageMstsForUpdatedUserId;
		this.orgUserMstsForCreatedUserId = orgUserMstsForCreatedUserId;
		this.cmnLanguageMstsForCreatedUserId = cmnLanguageMstsForCreatedUserId;
		this.orgUserImageMstsForCreatedUserId = orgUserImageMstsForCreatedUserId;
		this.orgUserMstsForUpdatedUserId = orgUserMstsForUpdatedUserId;
		this.orgUserRoleRltsForUpdatedUserId = orgUserRoleRltsForUpdatedUserId;
		this.orgRoleElementRltsForCreatedUserId = orgRoleElementRltsForCreatedUserId;
		this.orgUserRoleRltsForCreatedUserId = orgUserRoleRltsForCreatedUserId;
		this.orgEmpMstsForUpdatedUserId = orgEmpMstsForUpdatedUserId;
		this.orgRoleElementRltsForUpdatedUserId = orgRoleElementRltsForUpdatedUserId;
		this.orgElementDetailsRltsForUpdatedUserId = orgElementDetailsRltsForUpdatedUserId;
		this.orgElementDetailsRltsForCreatedUserId = orgElementDetailsRltsForCreatedUserId;
		this.orgUserImageMstsForUserId = orgUserImageMstsForUserId;
		this.orgElementMstsForCreatedUserId = orgElementMstsForCreatedUserId;
		this.orgRoleMstsForUpdatedUserId = orgRoleMstsForUpdatedUserId;
		this.cmnLookupMstsForCreatedUserId = cmnLookupMstsForCreatedUserId;
		this.cmnLookupDetailsRltsForCreatedUserId = cmnLookupDetailsRltsForCreatedUserId;
		this.orgElementMstsForUpdatedUserId = orgElementMstsForUpdatedUserId;
		this.cmnLookupDetailsRltsForUpdatedUserId = cmnLookupDetailsRltsForUpdatedUserId;
		this.orgRoleDetailsRltsForCreatedUserId = orgRoleDetailsRltsForCreatedUserId;
		this.orgRoleDetailsRltsForUpdatedUserId = orgRoleDetailsRltsForUpdatedUserId;
		this.orgEmpMstsForUserId = orgEmpMstsForUserId;
		this.cmnLanguageMstsForUpdatedUserId = cmnLanguageMstsForUpdatedUserId;
	}

	public long getUserId() {
		return userId;
	}

	public void setUserId(long userId) {
		this.userId = userId;
	}

	public OrgUserMst getOrgUserMstByCreatedUserId() {
		return orgUserMstByCreatedUserId;
	}

	public void setOrgUserMstByCreatedUserId(
			OrgUserMst orgUserMstByCreatedUserId) {
		this.orgUserMstByCreatedUserId = orgUserMstByCreatedUserId;
	}

	public OrgUserMst getOrgUserMstByUpdatedUserId() {
		return orgUserMstByUpdatedUserId;
	}

	public void setOrgUserMstByUpdatedUserId(
			OrgUserMst orgUserMstByUpdatedUserId) {
		this.orgUserMstByUpdatedUserId = orgUserMstByUpdatedUserId;
	}

	public String getUserName() {
		return userName;
	}

	public void setUserName(String userName) {
		this.userName = userName;
	}

	public String getPassword() {
		return password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	public boolean isActivateFlag() {
		return activateFlag;
	}

	public void setActivateFlag(boolean activateFlag) {
		this.activateFlag = activateFlag;
	}

	public Date getCreatedDate() {
		return createdDate;
	}

	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}

	public Date getUpdatedDate() {
		return updatedDate;
	}

	public void setUpdatedDate(Date updatedDate) {
		this.updatedDate = updatedDate;
	}

	public String getFirstlogin() {
		return firstlogin;
	}

	public void setFirstlogin(String firstlogin) {
		this.firstlogin = firstlogin;
	}

	public Date getPwdchangedDate() {
		return pwdchangedDate;
	}

	public void setPwdchangedDate(Date pwdchangedDate) {
		this.pwdchangedDate = pwdchangedDate;
	}

	public long getSecretQueCode() {
		return secretQueCode;
	}

	public void setSecretQueCode(long secretQueCode) {
		this.secretQueCode = secretQueCode;
	}

	public String getSecretAnswer() {
		return secretAnswer;
	}

	public void setSecretAnswer(String secretAnswer) {
		this.secretAnswer = secretAnswer;
	}

	public long getInvalidLoginCnt() {
		return invalidLoginCnt;
	}

	public void setInvalidLoginCnt(long invalidLoginCnt) {
		this.invalidLoginCnt = invalidLoginCnt;
	}

	public Date getUnlockTime() {
		return unlockTime;
	}

	public void setUnlockTime(Date unlockTime) {
		this.unlockTime = unlockTime;
	}

	public boolean isOtpEnabled() {
		return otpEnabled;
	}

	public void setOtpEnabled(boolean otpEnabled) {
		this.otpEnabled = otpEnabled;
	}

	public Long getOtp() {
		return otp;
	}

	public void setOtp(Long otp) {
		this.otp = otp;
	}

	public Date getOtpValidity() {
		return otpValidity;
	}

	public void setOtpValidity(Date otpValidity) {
		this.otpValidity = otpValidity;
	}

	public long getRegMobileNo() {
		return regMobileNo;
	}

	public void setRegMobileNo(long regMobileNo) {
		this.regMobileNo = regMobileNo;
	}

	public Set getOrgUserRoleRltsForUserId() {
		return orgUserRoleRltsForUserId;
	}

	public void setOrgUserRoleRltsForUserId(Set orgUserRoleRltsForUserId) {
		this.orgUserRoleRltsForUserId = orgUserRoleRltsForUserId;
	}

	public Set getOrgRoleMstsForCreatedUserId() {
		return orgRoleMstsForCreatedUserId;
	}

	public void setOrgRoleMstsForCreatedUserId(Set orgRoleMstsForCreatedUserId) {
		this.orgRoleMstsForCreatedUserId = orgRoleMstsForCreatedUserId;
	}

	public Set getOrgEmpMstsForCreatedUserId() {
		return orgEmpMstsForCreatedUserId;
	}

	public void setOrgEmpMstsForCreatedUserId(Set orgEmpMstsForCreatedUserId) {
		this.orgEmpMstsForCreatedUserId = orgEmpMstsForCreatedUserId;
	}

	public Set getCmnLookupMstsForUpdatedUserId() {
		return cmnLookupMstsForUpdatedUserId;
	}

	public void setCmnLookupMstsForUpdatedUserId(
			Set cmnLookupMstsForUpdatedUserId) {
		this.cmnLookupMstsForUpdatedUserId = cmnLookupMstsForUpdatedUserId;
	}

	public Set getOrgUserImageMstsForUpdatedUserId() {
		return orgUserImageMstsForUpdatedUserId;
	}

	public void setOrgUserImageMstsForUpdatedUserId(
			Set orgUserImageMstsForUpdatedUserId) {
		this.orgUserImageMstsForUpdatedUserId = orgUserImageMstsForUpdatedUserId;
	}

	public Set getOrgUserMstsForCreatedUserId() {
		return orgUserMstsForCreatedUserId;
	}

	public void setOrgUserMstsForCreatedUserId(Set orgUserMstsForCreatedUserId) {
		this.orgUserMstsForCreatedUserId = orgUserMstsForCreatedUserId;
	}

	public Set getCmnLanguageMstsForCreatedUserId() {
		return cmnLanguageMstsForCreatedUserId;
	}

	public void setCmnLanguageMstsForCreatedUserId(
			Set cmnLanguageMstsForCreatedUserId) {
		this.cmnLanguageMstsForCreatedUserId = cmnLanguageMstsForCreatedUserId;
	}

	public Set getOrgUserImageMstsForCreatedUserId() {
		return orgUserImageMstsForCreatedUserId;
	}

	public void setOrgUserImageMstsForCreatedUserId(
			Set orgUserImageMstsForCreatedUserId) {
		this.orgUserImageMstsForCreatedUserId = orgUserImageMstsForCreatedUserId;
	}

	public Set getOrgUserMstsForUpdatedUserId() {
		return orgUserMstsForUpdatedUserId;
	}

	public void setOrgUserMstsForUpdatedUserId(Set orgUserMstsForUpdatedUserId) {
		this.orgUserMstsForUpdatedUserId = orgUserMstsForUpdatedUserId;
	}

	public Set getOrgUserRoleRltsForUpdatedUserId() {
		return orgUserRoleRltsForUpdatedUserId;
	}

	public void setOrgUserRoleRltsForUpdatedUserId(
			Set orgUserRoleRltsForUpdatedUserId) {
		this.orgUserRoleRltsForUpdatedUserId = orgUserRoleRltsForUpdatedUserId;
	}

	public Set getOrgRoleElementRltsForCreatedUserId() {
		return orgRoleElementRltsForCreatedUserId;
	}

	public void setOrgRoleElementRltsForCreatedUserId(
			Set orgRoleElementRltsForCreatedUserId) {
		this.orgRoleElementRltsForCreatedUserId = orgRoleElementRltsForCreatedUserId;
	}

	public Set getOrgUserRoleRltsForCreatedUserId() {
		return orgUserRoleRltsForCreatedUserId;
	}

	public void setOrgUserRoleRltsForCreatedUserId(
			Set orgUserRoleRltsForCreatedUserId) {
		this.orgUserRoleRltsForCreatedUserId = orgUserRoleRltsForCreatedUserId;
	}

	public Set getOrgEmpMstsForUpdatedUserId() {
		return orgEmpMstsForUpdatedUserId;
	}

	public void setOrgEmpMstsForUpdatedUserId(Set orgEmpMstsForUpdatedUserId) {
		this.orgEmpMstsForUpdatedUserId = orgEmpMstsForUpdatedUserId;
	}

	public Set getOrgRoleElementRltsForUpdatedUserId() {
		return orgRoleElementRltsForUpdatedUserId;
	}

	public void setOrgRoleElementRltsForUpdatedUserId(
			Set orgRoleElementRltsForUpdatedUserId) {
		this.orgRoleElementRltsForUpdatedUserId = orgRoleElementRltsForUpdatedUserId;
	}

	public Set getOrgElementDetailsRltsForUpdatedUserId() {
		return orgElementDetailsRltsForUpdatedUserId;
	}

	public void setOrgElementDetailsRltsForUpdatedUserId(
			Set orgElementDetailsRltsForUpdatedUserId) {
		this.orgElementDetailsRltsForUpdatedUserId = orgElementDetailsRltsForUpdatedUserId;
	}

	public Set getOrgElementDetailsRltsForCreatedUserId() {
		return orgElementDetailsRltsForCreatedUserId;
	}

	public void setOrgElementDetailsRltsForCreatedUserId(
			Set orgElementDetailsRltsForCreatedUserId) {
		this.orgElementDetailsRltsForCreatedUserId = orgElementDetailsRltsForCreatedUserId;
	}

	public Set getOrgUserImageMstsForUserId() {
		return orgUserImageMstsForUserId;
	}

	public void setOrgUserImageMstsForUserId(Set orgUserImageMstsForUserId) {
		this.orgUserImageMstsForUserId = orgUserImageMstsForUserId;
	}

	public Set getOrgElementMstsForCreatedUserId() {
		return orgElementMstsForCreatedUserId;
	}

	public void setOrgElementMstsForCreatedUserId(
			Set orgElementMstsForCreatedUserId) {
		this.orgElementMstsForCreatedUserId = orgElementMstsForCreatedUserId;
	}

	public Set getOrgRoleMstsForUpdatedUserId() {
		return orgRoleMstsForUpdatedUserId;
	}

	public void setOrgRoleMstsForUpdatedUserId(Set orgRoleMstsForUpdatedUserId) {
		this.orgRoleMstsForUpdatedUserId = orgRoleMstsForUpdatedUserId;
	}

	public Set getCmnLookupMstsForCreatedUserId() {
		return cmnLookupMstsForCreatedUserId;
	}

	public void setCmnLookupMstsForCreatedUserId(
			Set cmnLookupMstsForCreatedUserId) {
		this.cmnLookupMstsForCreatedUserId = cmnLookupMstsForCreatedUserId;
	}

	public Set getCmnLookupDetailsRltsForCreatedUserId() {
		return cmnLookupDetailsRltsForCreatedUserId;
	}

	public void setCmnLookupDetailsRltsForCreatedUserId(
			Set cmnLookupDetailsRltsForCreatedUserId) {
		this.cmnLookupDetailsRltsForCreatedUserId = cmnLookupDetailsRltsForCreatedUserId;
	}

	public Set getOrgElementMstsForUpdatedUserId() {
		return orgElementMstsForUpdatedUserId;
	}

	public void setOrgElementMstsForUpdatedUserId(
			Set orgElementMstsForUpdatedUserId) {
		this.orgElementMstsForUpdatedUserId = orgElementMstsForUpdatedUserId;
	}

	public Set getCmnLookupDetailsRltsForUpdatedUserId() {
		return cmnLookupDetailsRltsForUpdatedUserId;
	}

	public void setCmnLookupDetailsRltsForUpdatedUserId(
			Set cmnLookupDetailsRltsForUpdatedUserId) {
		this.cmnLookupDetailsRltsForUpdatedUserId = cmnLookupDetailsRltsForUpdatedUserId;
	}

	public Set getOrgRoleDetailsRltsForCreatedUserId() {
		return orgRoleDetailsRltsForCreatedUserId;
	}

	public void setOrgRoleDetailsRltsForCreatedUserId(
			Set orgRoleDetailsRltsForCreatedUserId) {
		this.orgRoleDetailsRltsForCreatedUserId = orgRoleDetailsRltsForCreatedUserId;
	}

	public Set getOrgRoleDetailsRltsForUpdatedUserId() {
		return orgRoleDetailsRltsForUpdatedUserId;
	}

	public void setOrgRoleDetailsRltsForUpdatedUserId(
			Set orgRoleDetailsRltsForUpdatedUserId) {
		this.orgRoleDetailsRltsForUpdatedUserId = orgRoleDetailsRltsForUpdatedUserId;
	}

	public Set getOrgEmpMstsForUserId() {
		return orgEmpMstsForUserId;
	}

	public void setOrgEmpMstsForUserId(Set orgEmpMstsForUserId) {
		this.orgEmpMstsForUserId = orgEmpMstsForUserId;
	}

	public Set getCmnLanguageMstsForUpdatedUserId() {
		return cmnLanguageMstsForUpdatedUserId;
	}

	public void setCmnLanguageMstsForUpdatedUserId(
			Set cmnLanguageMstsForUpdatedUserId) {
		this.cmnLanguageMstsForUpdatedUserId = cmnLanguageMstsForUpdatedUserId;
	}

}
