package com.gargorg.Masters.valueObject;
// Generated May 9, 2014 11:23:19 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * OrgUserImageMst generated by hbm2java
 */
public class OrgUserImageMst implements java.io.Serializable {

	private static final long serialVersionUID = -7338773210001626340L;
	private long userImageId;
	private OrgUserMst orgUserMstByUserId;
	private OrgUserMst orgUserMstByCreatedUserId;
	private OrgUserMst orgUserMstByUpdatedUserId;
	private byte[] image;
	private boolean activateFlag;
	private Date createdDate;
	private Date updatedDate;
	private String encodedImageString;

	public OrgUserImageMst() {
	}

	public OrgUserImageMst(long userImageId, OrgUserMst orgUserMstByUserId,
			OrgUserMst orgUserMstByCreatedUserId, byte[] image,
			boolean activateFlag, Date createdDate) {
		this.userImageId = userImageId;
		this.orgUserMstByUserId = orgUserMstByUserId;
		this.orgUserMstByCreatedUserId = orgUserMstByCreatedUserId;
		this.image = image;
		this.activateFlag = activateFlag;
		this.createdDate = createdDate;
	}

	public OrgUserImageMst(long userImageId, OrgUserMst orgUserMstByUserId,
			OrgUserMst orgUserMstByCreatedUserId,
			OrgUserMst orgUserMstByUpdatedUserId, byte[] image,
			boolean activateFlag, Date createdDate, Date updatedDate) {
		this.userImageId = userImageId;
		this.orgUserMstByUserId = orgUserMstByUserId;
		this.orgUserMstByCreatedUserId = orgUserMstByCreatedUserId;
		this.orgUserMstByUpdatedUserId = orgUserMstByUpdatedUserId;
		this.image = image;
		this.activateFlag = activateFlag;
		this.createdDate = createdDate;
		this.updatedDate = updatedDate;
	}

	public long getUserImageId() {
		return this.userImageId;
	}

	public void setUserImageId(long userImageId) {
		this.userImageId = userImageId;
	}

	public OrgUserMst getOrgUserMstByUserId() {
		return this.orgUserMstByUserId;
	}

	public void setOrgUserMstByUserId(OrgUserMst orgUserMstByUserId) {
		this.orgUserMstByUserId = orgUserMstByUserId;
	}

	public OrgUserMst getOrgUserMstByCreatedUserId() {
		return this.orgUserMstByCreatedUserId;
	}

	public void setOrgUserMstByCreatedUserId(
			OrgUserMst orgUserMstByCreatedUserId) {
		this.orgUserMstByCreatedUserId = orgUserMstByCreatedUserId;
	}

	public OrgUserMst getOrgUserMstByUpdatedUserId() {
		return this.orgUserMstByUpdatedUserId;
	}

	public void setOrgUserMstByUpdatedUserId(
			OrgUserMst orgUserMstByUpdatedUserId) {
		this.orgUserMstByUpdatedUserId = orgUserMstByUpdatedUserId;
	}

	public byte[] getImage() {
		return this.image;
	}

	public void setImage(byte[] image) {
		this.image = image;
	}

	public boolean isActivateFlag() {
		return this.activateFlag;
	}

	public void setActivateFlag(boolean activateFlag) {
		this.activateFlag = activateFlag;
	}

	public Date getCreatedDate() {
		return this.createdDate;
	}

	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}

	public Date getUpdatedDate() {
		return this.updatedDate;
	}

	public void setUpdatedDate(Date updatedDate) {
		this.updatedDate = updatedDate;
	}
	
	public String getEncodedImageString() {
		return encodedImageString;
	}

	public void setEncodedImageString(String encodedImageString) {
		this.encodedImageString = encodedImageString;
	}
}
