package com.trainingportal.Masters.valueObject;

// Generated Nov 25, 2014 11:19:12 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

import com.gargorg.Masters.valueObject.OrgUserMst;

/**
 * OrgSkillMst generated by hbm2java
 */
public class OrgSkillMst implements java.io.Serializable {

	private static final long serialVersionUID = 8108322850877020380L;
	
	private long skillId;
	private OrgUserMst orgUserMstByCreatedUserId;
	private OrgUserMst orgUserMstByUpdatedUserId;
	private long skillCode;
	private String skillName;
	private String skillDesc;
	private boolean activateFlag;
	private Date createdDate;
	private Date updatedDate;

	public OrgSkillMst() {
	}

	public OrgSkillMst(long skillId, OrgUserMst orgUserMstByCreatedUserId,
			long skillCode, String skillName, boolean activateFlag,
			Date createdDate) {
		this.skillId = skillId;
		this.orgUserMstByCreatedUserId = orgUserMstByCreatedUserId;
		this.skillCode = skillCode;
		this.skillName = skillName;
		this.activateFlag = activateFlag;
		this.createdDate = createdDate;
	}

	public OrgSkillMst(long skillId, OrgUserMst orgUserMstByCreatedUserId,
			OrgUserMst orgUserMstByUpdatedUserId, long skillCode,
			String skillName, String skillDesc, boolean activateFlag,
			Date createdDate, Date updatedDate) {
		this.skillId = skillId;
		this.orgUserMstByCreatedUserId = orgUserMstByCreatedUserId;
		this.orgUserMstByUpdatedUserId = orgUserMstByUpdatedUserId;
		this.skillCode = skillCode;
		this.skillName = skillName;
		this.skillDesc = skillDesc;
		this.activateFlag = activateFlag;
		this.createdDate = createdDate;
		this.updatedDate = updatedDate;
	}

	public long getSkillId() {
		return this.skillId;
	}

	public void setSkillId(long skillId) {
		this.skillId = skillId;
	}

	public OrgUserMst getOrgUserMstByCreatedUserId() {
		return this.orgUserMstByCreatedUserId;
	}

	public void setOrgUserMstByCreatedUserId(
			OrgUserMst orgUserMstByCreatedUserId) {
		this.orgUserMstByCreatedUserId = orgUserMstByCreatedUserId;
	}

	public OrgUserMst getOrgUserMstByUpdatedUserId() {
		return this.orgUserMstByUpdatedUserId;
	}

	public void setOrgUserMstByUpdatedUserId(
			OrgUserMst orgUserMstByUpdatedUserId) {
		this.orgUserMstByUpdatedUserId = orgUserMstByUpdatedUserId;
	}

	public long getSkillCode() {
		return this.skillCode;
	}

	public void setSkillCode(long skillCode) {
		this.skillCode = skillCode;
	}

	public String getSkillName() {
		return this.skillName;
	}

	public void setSkillName(String skillName) {
		this.skillName = skillName;
	}

	public String getSkillDesc() {
		return this.skillDesc;
	}

	public void setSkillDesc(String skillDesc) {
		this.skillDesc = skillDesc;
	}

	public boolean isActivateFlag() {
		return this.activateFlag;
	}

	public void setActivateFlag(boolean activateFlag) {
		this.activateFlag = activateFlag;
	}

	public Date getCreatedDate() {
		return this.createdDate;
	}

	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}

	public Date getUpdatedDate() {
		return this.updatedDate;
	}

	public void setUpdatedDate(Date updatedDate) {
		this.updatedDate = updatedDate;
	}

}
