package com.trainingportal.Masters.valueObject;

// Generated Nov 25, 2014 11:19:12 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

import com.gargorg.Masters.valueObject.OrgUserMst;

/**
 * OrgTrainerSkillMpg generated by hbm2java
 */
public class OrgTrainerSkillMpg implements java.io.Serializable {

	private static final long serialVersionUID = 8713562184426665436L;
	
	private long trainerSkillMpgId;
	private OrgUserMst orgUserMstByCreatedUserId;
	private OrgUserMst orgUserMstByUpdatedUserId;
	private long trainerCode;
	private long skillCode;
	private boolean activateFlag;
	private Date createdDate;
	private Date updatedDate;

	public OrgTrainerSkillMpg() {
	}

	public OrgTrainerSkillMpg(long trainerSkillMpgId,
			OrgUserMst orgUserMstByCreatedUserId, long trainerCode,
			long skillCode, boolean activateFlag, Date createdDate) {
		this.trainerSkillMpgId = trainerSkillMpgId;
		this.orgUserMstByCreatedUserId = orgUserMstByCreatedUserId;
		this.trainerCode = trainerCode;
		this.skillCode = skillCode;
		this.activateFlag = activateFlag;
		this.createdDate = createdDate;
	}

	public OrgTrainerSkillMpg(long trainerSkillMpgId,
			OrgUserMst orgUserMstByCreatedUserId,
			OrgUserMst orgUserMstByUpdatedUserId, long trainerCode,
			long skillCode, boolean activateFlag, Date createdDate,
			Date updatedDate) {
		this.trainerSkillMpgId = trainerSkillMpgId;
		this.orgUserMstByCreatedUserId = orgUserMstByCreatedUserId;
		this.orgUserMstByUpdatedUserId = orgUserMstByUpdatedUserId;
		this.trainerCode = trainerCode;
		this.skillCode = skillCode;
		this.activateFlag = activateFlag;
		this.createdDate = createdDate;
		this.updatedDate = updatedDate;
	}

	public long getTrainerSkillMpgId() {
		return this.trainerSkillMpgId;
	}

	public void setTrainerSkillMpgId(long trainerSkillMpgId) {
		this.trainerSkillMpgId = trainerSkillMpgId;
	}

	public OrgUserMst getOrgUserMstByCreatedUserId() {
		return this.orgUserMstByCreatedUserId;
	}

	public void setOrgUserMstByCreatedUserId(
			OrgUserMst orgUserMstByCreatedUserId) {
		this.orgUserMstByCreatedUserId = orgUserMstByCreatedUserId;
	}

	public OrgUserMst getOrgUserMstByUpdatedUserId() {
		return this.orgUserMstByUpdatedUserId;
	}

	public void setOrgUserMstByUpdatedUserId(
			OrgUserMst orgUserMstByUpdatedUserId) {
		this.orgUserMstByUpdatedUserId = orgUserMstByUpdatedUserId;
	}

	public long getTrainerCode() {
		return this.trainerCode;
	}

	public void setTrainerCode(long trainerCode) {
		this.trainerCode = trainerCode;
	}

	public long getSkillCode() {
		return this.skillCode;
	}

	public void setSkillCode(long skillCode) {
		this.skillCode = skillCode;
	}

	public boolean isActivateFlag() {
		return this.activateFlag;
	}

	public void setActivateFlag(boolean activateFlag) {
		this.activateFlag = activateFlag;
	}

	public Date getCreatedDate() {
		return this.createdDate;
	}

	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}

	public Date getUpdatedDate() {
		return this.updatedDate;
	}

	public void setUpdatedDate(Date updatedDate) {
		this.updatedDate = updatedDate;
	}

}
